title: EXPRESS Language Foundation Schemas
description: Official EXPRESS Language Foundation schemas site
baseurl: /schemas
url: https://expresslang.github.io
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-asciidoc
  - jekyll-remote-theme
  - jekyll-seo-tag

asciidoc: {}

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=rouge
    - icons=font
